language: node_js
node_js:
  - "10.16"
dist: trusty
addons:
  chrome: stable
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
after_success:
  - npm run-script build
before_deploy:
  - ./.travis_scripts/replace_path.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $DEPLOY_TOKEN
  local_dir: ./dist/todo-web/
  repo: Delorus/todo
  target_branch: gh-pages
  on:
    branch: master
branches:
  only:
    - master
